//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClient3D.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputForTempBase", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Temperature")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPFClient3D.ServiceReference1.InputForTemp3D))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPFClient3D.ServiceReference1.InputForTemp1D))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPFClient3D.ServiceReference1.InputForTemp))]
    public partial class InputForTempBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InputMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeStepsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double C {
            get {
                return this.CField;
            }
            set {
                if ((this.CField.Equals(value) != true)) {
                    this.CField = value;
                    this.RaisePropertyChanged("C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double H {
            get {
                return this.HField;
            }
            set {
                if ((this.HField.Equals(value) != true)) {
                    this.HField = value;
                    this.RaisePropertyChanged("H");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputMessage {
            get {
                return this.InputMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InputMessageField, value) != true)) {
                    this.InputMessageField = value;
                    this.RaisePropertyChanged("InputMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Tau {
            get {
                return this.TauField;
            }
            set {
                if ((this.TauField.Equals(value) != true)) {
                    this.TauField = value;
                    this.RaisePropertyChanged("Tau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeSteps {
            get {
                return this.TimeStepsField;
            }
            set {
                if ((this.TimeStepsField.Equals(value) != true)) {
                    this.TimeStepsField = value;
                    this.RaisePropertyChanged("TimeSteps");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputForTemp3D", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Temperature")]
    [System.SerializableAttribute()]
    public partial class InputForTemp3D : WPFClient3D.ServiceReference1.InputForTempBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Array3DLibrary.Array3D<double> UField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Array3DLibrary.Array3D<double> U {
            get {
                return this.UField;
            }
            set {
                if ((object.ReferenceEquals(this.UField, value) != true)) {
                    this.UField = value;
                    this.RaisePropertyChanged("U");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputForTemp1D", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Temperature")]
    [System.SerializableAttribute()]
    public partial class InputForTemp1D : WPFClient3D.ServiceReference1.InputForTempBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] UField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] U {
            get {
                return this.UField;
            }
            set {
                if ((object.ReferenceEquals(this.UField, value) != true)) {
                    this.UField = value;
                    this.RaisePropertyChanged("U");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputForTemp", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Temperature")]
    [System.SerializableAttribute()]
    public partial class InputForTemp : WPFClient3D.ServiceReference1.InputForTempBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] UField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] U {
            get {
                return this.UField;
            }
            set {
                if ((object.ReferenceEquals(this.UField, value) != true)) {
                    this.UField = value;
                    this.RaisePropertyChanged("U");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputForTempBase", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Temperature")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPFClient3D.ServiceReference1.OutputForTemp3D))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPFClient3D.ServiceReference1.OutputForTemp1D))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPFClient3D.ServiceReference1.OutputForTemp))]
    public partial class OutputForTempBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputMessage {
            get {
                return this.OutputMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputMessageField, value) != true)) {
                    this.OutputMessageField = value;
                    this.RaisePropertyChanged("OutputMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputForTemp3D", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Temperature")]
    [System.SerializableAttribute()]
    public partial class OutputForTemp3D : WPFClient3D.ServiceReference1.OutputForTempBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Array3DLibrary.Array3D<double> UField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Array3DLibrary.Array3D<double> U {
            get {
                return this.UField;
            }
            set {
                if ((object.ReferenceEquals(this.UField, value) != true)) {
                    this.UField = value;
                    this.RaisePropertyChanged("U");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputForTemp1D", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Temperature")]
    [System.SerializableAttribute()]
    public partial class OutputForTemp1D : WPFClient3D.ServiceReference1.OutputForTempBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] UField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] U {
            get {
                return this.UField;
            }
            set {
                if ((object.ReferenceEquals(this.UField, value) != true)) {
                    this.UField = value;
                    this.RaisePropertyChanged("U");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputForTemp", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Temperature")]
    [System.SerializableAttribute()]
    public partial class OutputForTemp : WPFClient3D.ServiceReference1.OutputForTempBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] UField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] U {
            get {
                return this.UField;
            }
            set {
                if ((object.ReferenceEquals(this.UField, value) != true)) {
                    this.UField = value;
                    this.RaisePropertyChanged("U");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatrixInput", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Matrix")]
    [System.SerializableAttribute()]
    public partial class MatrixInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] matrix1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] matrix2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] matrix1 {
            get {
                return this.matrix1Field;
            }
            set {
                if ((object.ReferenceEquals(this.matrix1Field, value) != true)) {
                    this.matrix1Field = value;
                    this.RaisePropertyChanged("matrix1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] matrix2 {
            get {
                return this.matrix2Field;
            }
            set {
                if ((object.ReferenceEquals(this.matrix2Field, value) != true)) {
                    this.matrix2Field = value;
                    this.RaisePropertyChanged("matrix2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatrixOutput", Namespace="http://schemas.datacontract.org/2004/07/WcfMathLibrary.Matrix")]
    [System.SerializableAttribute()]
    public partial class MatrixOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] matrixResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] matrixResult {
            get {
                return this.matrixResultField;
            }
            set {
                if ((object.ReferenceEquals(this.matrixResultField, value) != true)) {
                    this.matrixResultField = value;
                    this.RaisePropertyChanged("matrixResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateTemp", ReplyAction="http://tempuri.org/IService/CalculateTempResponse")]
        WPFClient3D.ServiceReference1.OutputForTemp CalculateTemp(WPFClient3D.ServiceReference1.InputForTemp input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateTemp", ReplyAction="http://tempuri.org/IService/CalculateTempResponse")]
        System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.OutputForTemp> CalculateTempAsync(WPFClient3D.ServiceReference1.InputForTemp input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateTemp3D", ReplyAction="http://tempuri.org/IService/CalculateTemp3DResponse")]
        WPFClient3D.ServiceReference1.OutputForTemp3D CalculateTemp3D(WPFClient3D.ServiceReference1.InputForTemp3D input3D);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateTemp3D", ReplyAction="http://tempuri.org/IService/CalculateTemp3DResponse")]
        System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.OutputForTemp3D> CalculateTemp3DAsync(WPFClient3D.ServiceReference1.InputForTemp3D input3D);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateTemp1D", ReplyAction="http://tempuri.org/IService/CalculateTemp1DResponse")]
        WPFClient3D.ServiceReference1.OutputForTemp1D CalculateTemp1D(WPFClient3D.ServiceReference1.InputForTemp1D input1D);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateTemp1D", ReplyAction="http://tempuri.org/IService/CalculateTemp1DResponse")]
        System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.OutputForTemp1D> CalculateTemp1DAsync(WPFClient3D.ServiceReference1.InputForTemp1D input1D);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MatrixSum", ReplyAction="http://tempuri.org/IService/MatrixSumResponse")]
        WPFClient3D.ServiceReference1.MatrixOutput MatrixSum(WPFClient3D.ServiceReference1.MatrixInput Input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MatrixSum", ReplyAction="http://tempuri.org/IService/MatrixSumResponse")]
        System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.MatrixOutput> MatrixSumAsync(WPFClient3D.ServiceReference1.MatrixInput Input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MatrixMul", ReplyAction="http://tempuri.org/IService/MatrixMulResponse")]
        WPFClient3D.ServiceReference1.MatrixOutput MatrixMul(WPFClient3D.ServiceReference1.MatrixInput Input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MatrixMul", ReplyAction="http://tempuri.org/IService/MatrixMulResponse")]
        System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.MatrixOutput> MatrixMulAsync(WPFClient3D.ServiceReference1.MatrixInput Input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WPFClient3D.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WPFClient3D.ServiceReference1.IService>, WPFClient3D.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPFClient3D.ServiceReference1.OutputForTemp CalculateTemp(WPFClient3D.ServiceReference1.InputForTemp input) {
            return base.Channel.CalculateTemp(input);
        }
        
        public System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.OutputForTemp> CalculateTempAsync(WPFClient3D.ServiceReference1.InputForTemp input) {
            return base.Channel.CalculateTempAsync(input);
        }
        
        public WPFClient3D.ServiceReference1.OutputForTemp3D CalculateTemp3D(WPFClient3D.ServiceReference1.InputForTemp3D input3D) {
            return base.Channel.CalculateTemp3D(input3D);
        }
        
        public System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.OutputForTemp3D> CalculateTemp3DAsync(WPFClient3D.ServiceReference1.InputForTemp3D input3D) {
            return base.Channel.CalculateTemp3DAsync(input3D);
        }
        
        public WPFClient3D.ServiceReference1.OutputForTemp1D CalculateTemp1D(WPFClient3D.ServiceReference1.InputForTemp1D input1D) {
            return base.Channel.CalculateTemp1D(input1D);
        }
        
        public System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.OutputForTemp1D> CalculateTemp1DAsync(WPFClient3D.ServiceReference1.InputForTemp1D input1D) {
            return base.Channel.CalculateTemp1DAsync(input1D);
        }
        
        public WPFClient3D.ServiceReference1.MatrixOutput MatrixSum(WPFClient3D.ServiceReference1.MatrixInput Input) {
            return base.Channel.MatrixSum(Input);
        }
        
        public System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.MatrixOutput> MatrixSumAsync(WPFClient3D.ServiceReference1.MatrixInput Input) {
            return base.Channel.MatrixSumAsync(Input);
        }
        
        public WPFClient3D.ServiceReference1.MatrixOutput MatrixMul(WPFClient3D.ServiceReference1.MatrixInput Input) {
            return base.Channel.MatrixMul(Input);
        }
        
        public System.Threading.Tasks.Task<WPFClient3D.ServiceReference1.MatrixOutput> MatrixMulAsync(WPFClient3D.ServiceReference1.MatrixInput Input) {
            return base.Channel.MatrixMulAsync(Input);
        }
    }
}
